# Generated by Django 3.1.7 on 2021-04-07 04:00

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=''),
        ),
    ]
