# Generated by Django 3.1.7 on 2021-04-07 04:25

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210407_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(auto_created=True, blank=True, upload_to=''),
        ),
    ]
